mylist = ("apple", "banana", "apple","Oranges",1,2,3,4)
print(mylist)
print(mylist.index("banana"))
print(mylist.index("banana", 1))
print(len(mylist))
print(4*mylist)
print(mylist+mylist)
print(type(mylist))
print(mylist[0:3])